language: ruby
cache: bundler
sudo: false

rvm:
  - 2.0.0
  - 2.1
  - 2.2

env:
  - BUILD_SOURCE=1
  - SOURCE_VERSION="~>1.14.0"
  - SOURCE_VERSION="~>1.15.0"
  - SOURCE_VERSION="~>2.0.0"
  - SOURCE_VERSION="~>2.1.0"
  - SOURCE_VERSION="~>2.1.0"
  - SOURCE_VERSION="~>2.2.0"
  - SOURCE_VERSION="~>2.3.0"
  - SOURCE_VERSION="~>2.4.0"
  - SOURCE_VERSION="~>2.5.0"
  - SOURCE_VERSION="~>2.6.0"
  - SOURCE_VERSION="~>2.7.0"
  - SOURCE_VERSION="~>2.8.0"
  - SOURCE_VERSION="~>2.9.0"
  - SOURCE_VERSION="~>2.10.0"
  - SOURCE_VERSION="~>2.11.0"
  - SOURCE_VERSION="~>2.12.0"
  - SOURCE_VERSION="~>2.13.0"
  - SOURCE_VERSION="~>3.0.0"
  - SOURCE_VERSION="~>3.1.0"
  - SOURCE_VERSION="~>3.2.0"
  - SOURCE_VERSION="~>3.3.0"
