language: ruby
cache: bundler
sudo: false

script: ./script/test
after_success: ./script/deploy

rvm:
  - 2.0.0
  - 2.1
  - 2.2

env:
  global:
    secure: "XT/kMVPucmliC0l0Or2l3Za43l4sYt5fhX2ISkfb1OnJezIa+mgGTSPCpi1cBx+NPSCV96qyIP0Fybhb+pI/UQFhvzPTP26HfmrXN7TmQfesPgIS6wYQZc79GyNW93am5NQBqFISuriAMCgkdlmNAYcWYMGvLvKeyUDPAjgIzVM="
  matrix:
    - BUILD_SOURCE_GEM=1
    - VALIDATE_TRAVIS=1
    - SOURCE_VERSION="~>4.0.0"
    - SOURCE_VERSION="~>4.1.0"
    - SOURCE_VERSION="~>4.2.0"
    - SOURCE_VERSION="~>4.3.0"

matrix:
  allow_failures:
    - env: VALIDATE_TRAVIS=1
